services:
  recipes_api:
    # when build - executes Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    volumes:
      - postgres_data:/var/lib/postgresql/data

# persistent data volumes
volumes:
  postgres_data:
  dev-static-data:

########################################################################
# Building image
# docker-compose build
# docker compose up --build

# Linting - Install flake8, .flake8 in root directory, to exclude some files linting
#  docker-compose run --rm recipes_api sh -c "flake8"

# Testing
#docker-compose run --rm --remove-orphans recipes_api sh -c "python manage.py test"

# starting services - test on http://127.0.0.1:8000/
# docker-compose up
# docker-compose run --rm recipes_api sh -c "python manage.py migrate"docker-compose run --rm recipes_api sh -c "python manage.py makemigrations"
# docker-compose run --rm recipes_api sh -c "python manage.py migrate"

# docker-compose run --rm recipes_api sh -c "python manage.py createsuperuser"

# docker-compose run --rm recipes_api sh -c "python manage.py startapp user"
# docker-compose run --rm recipes_api sh -c "python manage.py startapp recipe"
#  docker-compose run --rm recipes_api sh -c "python -m pip install --upgrade pip"
# docker-compose run --rm recipes_api sh -c "python -m pip install Pillow"
# docker-compose run --rm recipes_api sh -c "python -m pip freeze > requirements.txt"