---
name: Checks
# run-name: ${{github.actor}} performed ${{github.event_name}} on ${{github.head_ref || github.ref_name}}

# the GitHub event that triggers workflow
on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Build and Run Tests
#        run: docker compose run --rm recipes_api sh -c "python manage.py test && flake8"

      - name: Test
        run: docker compose run --rm recipes_api sh -c "python manage.py wait_for_db && python manage.py test"

      - name: Linting
        run: docker compose run --rm recipes_api sh -c "flake8"
